---
title: "Thesis progress"
author: "WJ Bakker"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 3
---



```{r, message=FALSE, warning=FALSE, include = FALSE}

library(glmnet)
library(tidyverse)
library(ggplot2)
library(stargazer)


```



# Introduction

### General summary of what I plan to do (so far)

In this paper, I would like to develop methods for applying panel data techniques to survey data. Panel data concern repeated measurements for multiple cross-sectional units over time. However, in many cases true panel data are not available. For example, panel data methods are effective in analysing labour mobility to the end of improving public policies, but data are generally not available for the same workers over time (Ribas, 2022). However, survey data may be available, where representative samples for each cross-sectional unit are observed at each timepoint. In order to leverage the methods for panel data analysis, this dimension ought to be reduced to obtain single measurements for each timepoint. 

[Deaton (1985)](https://www.princeton.edu/~deaton/downloads/Panel_Data_from_Time_Series_of_Cross_Sections.pdf) first proposes methods to construct these pseudo-panel data by taking population averages. However, this method only works if the survey is a representative sample from the population, which can be an overly strong assumption. Sampling bias is one potential issue. One source of sampling bias is the result of missing values, which leads to dropped observations. Moreover, sampling bias can occur in the data collection when some sub-populations have a larger tendency to respond to the survey. The means, then, will not estimate the population average, lead to an unrepresentative pseudo-panel dataset and ultimately to incorrect inference. 

To solve this, one would need data on the distribution of the relevant sub-populations. If we assume that there is no sampling bias in the data collection, one can use the sub-population distributions of the full dataset and then use them to correct for the bias in the cleaned data. To correct for both sources of sampling bias one could use publicly available information of sub-population distributions, with the downside that it is time-consuming for a large number of cross-sectional units. 

With knowledge of the sub-population distributions the bias can be corrected. Two methods will be compared: using a weighted average (instead of the unweighted average as used by Deaton (1985)), and using stratified bootstrapping (NOTE: I will have to research whether stratified bootstrapping provides any advantages; it provides a distribution of the mean instead of a point estimate, but I'm not sure whether this is relevant for a pseudo-panel analysis).

The research is motivated by the CSES dataset. From their website, "The Comparative Study of Electoral Systems (CSES) is a collaborative program of research among election study teams from around the world. Participating countries and provinces include a common module of survey questions in their post-election studies. The resulting data are deposited along with voting, demographic, district and macro/electoral system variables. The studies are then merged into a single, free, public dataset for use in comparative study and cross-level analysis." (see: https://cses.org/about-the-study/)

To this end, I will first perform a simulation study, generating data that reflect the CSES survey data. Then, I will construct a pseudo-panel dataset using the aforementioned methods and perform a panel data analysis, and see whether the outcome reflects the DGP of the simulated data. The requirements for the data used for the pseudo-panel data analysis will be analysed by simulating data with varying characteristics. 


## Ideas for analysis

- **Democratic Satisfaction**
  - **Variable**: Satisfaction with the way democracy works in the respondent's country.
  - **Interest**: Exploring the factors that influence democratic satisfaction and how it impacts electoral behavior.

- **Policy Preferences**
  - **Variable**: Preferences for specific policies (e.g., economic policies, social policies, immigration policies).
  - **Interest**: Analyzing the relationship between policy preferences and voting behavior or party support.

- **Economic Perceptions**
  - **Variable**: Perception of the national or personal economic situation.
  - **Interest**: Studying how economic perceptions influence voting behavior and political attitudes.

- **Political Trust**
  - **Variable**: Level of trust in political institutions (e.g., trust in government, parliament, or judiciary).
  - **Interest**: Examining the determinants of political trust and how it varies across countries and over time.




## Comments on the introduction

We previously discussed the model from [Su, Shi, & Phillips](https://doi-org.vu-nl.idm.oclc.org/10.3982/ECTA12560). It can still be interesting to apply and use it as a sub-research question, but it feels like then the scope of my thesis might become a little too big. This is still something that I consider of course, since I think that there is reason to believe that the assumption of slope homogeneity might be too strong. 

Moreover, I am of course aware that a panel data model should model some underlying characteristic of the data. Although left-right vote could still be interesting, I don't think this is suitable for the methods I described above, and there might be a better method to answer my question: factors that determine the political developments in Europe. 
This is my idea currently:

- data are available for the percentage of votes each party obtained
- data are available for the left-rightness of each party's manifesto (using the CMP data)

Using this I can calculate the left-rightness of a country: mean(% votes * left-rightness), which is essentially the mean of the weighted left-rightness of each party. I can then still use the other data that are collected in the CSES as independent variables. I am still a bit unsure on how I would work this out though.

Alternatively, I could still use the left-right vote of each individual, and if I can assume that the sample is representative, taking the mean (even though it is a categorical variable) should still be valid.

 
Another option: only analyse the Netherlands, use parties as cross-sectional units (like we discussed in meeting 1). This has several benefits, most notably the matching time indices. I can then use one of the ideas for analysis for panel data analysis, although I will have to work out the variables more thoroughly.

# Methods

First we perform a simulation study. Two problems for survey data are notable: missingness and non-representativeness, factors which also mutually influence each other. First we generate a full population, from which we sample using stratified sampling, a common sampling technique. Stratas are mutually exclusive cohorts, such as gender, birthyear, etc. When sampling is performed properly, several techniques can be applied, which will be compared. Standard statistical techniques can be applied and will result in unbiased estimators when a few key assumptions are met:

- There are no missing data
  - Or, if there are missing data, they are Missing At Random (MAR)
- The data for each strata are normally distributed
  - Or, if the data are not normally distributed, sufficient samples are taken for the CLT to hold

To this end, we first show that the true population parameters can be estimated using representative subsamples when these three conditions hold. Then, the conditions will be varied. The most basic statistical technique that is relevant for surveys is estimating the population mean. For the application of pseudo-panel methods this is essential, since the population mean is the most straightforward way to construct a pseudo panel.  

An alternative method to construct pseudo panel data is by using regression techniques. Here, in addition to the no missing data assumption, additional assumptions apply. (TODO: need to read the papers and see what they say.)


First, we deal with the assumption of missing data. One problem occurs when missing data are Not Missing At Random (NMAR). For example, some cohorts might be more prone to non-response for certain questions, for example questions regarding religion, political opinions when their opinions are deemed controversial, etc. Applying methods directly to these data will lead to biased estimators. One possible solution is imputation: filling the missing values using estimation procedures. Another solution is balancing: weighting the underrepresented cohorts more heavily.

Another possible problem is non-normality in the data. First, the goal is to determine the effect of non-normality under different conditions: no missing data, MAR, NMAR. Additionally, the minimum sample size at which missingness is no longer a problem can be determined. 

- **Problem:** Missing data are NMAR
  - **Solutions:** 
    - Imputation
    - Balancing
- **Problem:** Data are not normally distributed
  - **Solutions:**
    - Bootstrapping
    - Model the population mean with techniques that are robust to non-normality (TODO: this should be possible, need to research this further)
    
    










